"use client";

import { useEffect, useRef } from "react";
import { motion, useInView } from "framer-motion";
import { useAuditStore } from "@/lib/use-audit";
import { MOCK_AUDIT } from "@/lib/audit-data";
import type { AuditData } from "@/lib/audit-data";
import { IssueCard } from "@/components/audit/v2/IssueCard";
import { TrafficOpportunityCard } from "@/components/audit/v2/TrafficOpportunityCard";
import { NicheBenchmarkWidget } from "@/components/audit/v2/NicheBenchmarkWidget";
import { ArrowRight, Activity } from "lucide-react";

// Low-score mock so the widgets show maximum "opportunity"
const LANDING_MOCK: AuditData = {
  domain: "yoursite.com",
  score: 30,
  scoreHistory: [
    { date: "2025-10-01", score: 18 },
    { date: "2025-11-01", score: 22 },
    { date: "2025-12-01", score: 26 },
    { date: "2026-01-01", score: 28 },
    { date: "2026-02-01", score: 30 },
  ],
  lastScanned: new Date().toISOString(),
  estimatedTrafficLoss: { min: 15, max: 25 },
  confidence: "High",
  categories: [
    { name: "Technical SEO", score: 22, benchmark: 65 },
    { name: "On-Page SEO", score: 41, benchmark: 68 },
    { name: "Performance", score: 28, benchmark: 72 },
    { name: "Mobile", score: 35, benchmark: 70 },
  ],
  issues: [
    {
      id: "lp-orphan-pages",
      priority: "critical",
      status: "open",
      title: "Orphan Pages Not Indexed",
      description:
        "Multiple pages have no internal links pointing to them. Canonical tags and internal linking are critical for ensuring Googlebot discovers and indexes your full content.",
      impact: "Losing 35% of potential crawl coverage",
      trafficImpact: { min: 420, max: 1200 },
      timeEstimateMinutes: 30,
      howToFix: [
        "Audit your sitemap for pages missing internal links.",
        "Add contextual links from high-authority pages on your site.",
        "Submit the updated sitemap in Google Search Console.",
      ],
      serpBefore: {
        title: "Our Blog - YourSite",
        url: "yoursite.com/blog/article-not-indexed",
        description: "Read our latest insights...",
      },
      serpAfter: {
        title: "Our Blog - YourSite | SEO Best Practices",
        url: "yoursite.com/blog/article-now-indexed",
        description: "Read our actionable SEO guides and grow your organic traffic.",
      },
      affectedPages: ["/blog/post-1", "/blog/post-2", "/docs/guide"],
      category: "Technical SEO",
    },
    {
      id: "lp-canonical-mismatch",
      priority: "high",
      status: "open",
      title: "Canonical Tags Point to Wrong URL",
      description:
        "Your canonical tags reference the www version but Google indexes the non-www version, splitting PageRank and Core Web Vitals signals across two separate URLs.",
      impact: "Splitting PageRank across 2 URLs",
      trafficImpact: { min: 180, max: 600 },
      timeEstimateMinutes: 10,
      howToFix: [
        "Decide on www vs non-www as your canonical domain.",
        'Update all <link rel="canonical"> tags to match your preferred domain.',
        "Set up a 301 redirect from the non-preferred variant.",
        "Verify in Google Search Console under Coverage.",
      ],
      serpBefore: {
        title: "Home - YourSite.com",
        url: "www.yoursite.com/ and yoursite.com/",
        description: "Welcome to our site...",
      },
      serpAfter: {
        title: "Home - YourSite.com",
        url: "yoursite.com/",
        description: "Welcome to our site — one authoritative URL.",
      },
      category: "Technical SEO",
    },
    {
      id: "lp-meta-missing",
      priority: "medium",
      status: "open",
      title: "Meta Descriptions Missing on 14 Pages",
      description:
        "Google auto-generates meta descriptions when they're missing — usually pulling random text that destroys your CTR. Writing optimised descriptions directly improves click-through rates.",
      impact: "Up to 30% lower CTR in search results",
      trafficImpact: { min: 80, max: 350 },
      timeEstimateMinutes: 20,
      howToFix: [
        "List all pages missing meta descriptions using the Affected Pages list below.",
        "Write 150–160 character descriptions with a clear value proposition.",
        "Include your target keyword naturally in the description.",
      ],
      serpBefore: {
        title: "Services - YourSite",
        url: "yoursite.com/services",
        description: "YourSite.com — services page content auto-generated by Google...",
      },
      serpAfter: {
        title: "Services - YourSite",
        url: "yoursite.com/services",
        description: "Explore our full range of services designed to grow your business. Get started today.",
      },
      affectedPages: ["/services", "/about", "/contact", "/pricing", "/blog"],
      category: "On-Page SEO",
    },
  ],
  competitors: [
    { domain: "competitor-a.com", score: 71 },
    { domain: "competitor-b.com", score: 65 },
  ],
  roadmap: [
    { issueId: "lp-orphan-pages", order: 1, isLocked: false },
    { issueId: "lp-canonical-mismatch", order: 2, isLocked: false },
    { issueId: "lp-meta-missing", order: 3, isLocked: true },
  ],
};

// Animated SVG score gauge
function ScoreGauge({ score }: { score: number }) {
  const ref = useRef<SVGCircleElement>(null);
  const containerRef = useRef<HTMLDivElement>(null);
  const inView = useInView(containerRef, { once: true, margin: "-80px" });

  const radius = 54;
  const circumference = 2 * Math.PI * radius;
  const pct = score / 100;
  const dashOffset = circumference * (1 - pct);

  const scoreColor =
    score < 40 ? "#EF4444" : score < 65 ? "#f59e0b" : "#10B981";

  return (
    <div ref={containerRef} className="flex flex-col items-center gap-2">
      <svg width="140" height="140" viewBox="0 0 140 140">
        {/* Track */}
        <circle
          cx="70"
          cy="70"
          r={radius}
          fill="none"
          stroke="rgba(255,255,255,0.06)"
          strokeWidth="10"
          strokeLinecap="round"
        />
        {/* Progress */}
        <motion.circle
          ref={ref}
          cx="70"
          cy="70"
          r={radius}
          fill="none"
          stroke={scoreColor}
          strokeWidth="10"
          strokeLinecap="round"
          strokeDasharray={circumference}
          initial={{ strokeDashoffset: circumference }}
          animate={inView ? { strokeDashoffset: dashOffset } : { strokeDashoffset: circumference }}
          transition={{ duration: 1.2, ease: "easeOut", delay: 0.3 }}
          transform="rotate(-90 70 70)"
          style={{ filter: `drop-shadow(0 0 8px ${scoreColor}60)` }}
        />
        {/* Score text */}
        <text x="70" y="65" textAnchor="middle" fill={scoreColor} fontSize="28" fontWeight="700">
          {score}
        </text>
        <text x="70" y="83" textAnchor="middle" fill="#64748b" fontSize="11">
          / 100
        </text>
      </svg>
      <span
        className="rounded-full border px-3 py-1 text-xs font-semibold"
        style={{
          color: scoreColor,
          borderColor: `${scoreColor}30`,
          background: `${scoreColor}10`,
        }}
      >
        {score < 40 ? "⚠ Needs Work" : score < 65 ? "⚡ Fair" : "✓ Good"}
      </span>
    </div>
  );
}

export function AuditPreviewSection() {
  const { setData } = useAuditStore();

  useEffect(() => {
    setData(LANDING_MOCK);
    return () => {
      // Restore default mock on unmount so other pages aren't affected
      setData(MOCK_AUDIT);
    };
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <section className="relative overflow-hidden bg-black py-32">
      {/* Background glow */}
      <div className="pointer-events-none absolute left-1/2 top-0 h-[500px] w-[700px] -translate-x-1/2 rounded-full bg-[#FF642D]/5 blur-[120px]" />

      <div className="relative mx-auto max-w-7xl px-6">
        {/* Section header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-60px" }}
          transition={{ duration: 0.6 }}
          className="mb-16 text-center"
        >
          <div className="mb-4 inline-flex items-center gap-2 rounded-full border border-[#FF642D]/30 bg-[#FF642D]/10 px-4 py-1.5">
            <Activity size={13} className="text-[#FF642D]" />
            <span className="text-xs font-semibold uppercase tracking-widest text-[#FF642D]">
              Live Preview
            </span>
          </div>
          <h2
            className="font-['Fraunces'] font-bold leading-tight text-white"
            style={{ fontSize: "clamp(28px, 4vw, 48px)" }}
          >
            Actionable data at a glance.
          </h2>
          <p className="mx-auto mt-4 max-w-xl text-base text-slate-400">
            This is a real render of the RankyPulse audit engine — site health score, traffic opportunity, and niche benchmarks all in one view.
          </p>
        </motion.div>

        {/* Two-column layout */}
        <div className="grid items-start gap-8 lg:grid-cols-12">
          {/* Left col: score + issues */}
          <motion.div
            initial={{ opacity: 0, x: -20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, margin: "-60px" }}
            transition={{ duration: 0.6 }}
            className="space-y-5 lg:col-span-5"
          >
            {/* Score card */}
            <div className="rounded-2xl border border-white/[0.06] bg-white/[0.02] p-6 text-center">
              <p className="mb-4 font-['DM_Mono'] text-[10px] uppercase tracking-widest text-slate-600">
                Site Health Score
              </p>
              <ScoreGauge score={LANDING_MOCK.score} />
              <p className="mt-4 text-xs text-slate-500">
                yoursite.com · scanned just now
              </p>
            </div>

            {/* Issue cards */}
            <div className="space-y-3">
              {LANDING_MOCK.issues.map((issue) => (
                <IssueCard
                  key={issue.id}
                  issue={issue}
                  isExpanded={false}
                  isHighlighted={false}
                  onToggleExpand={() => {}}
                  onMarkFixed={() => {}}
                />
              ))}
            </div>

            {/* CTA */}
            <a
              href="/"
              className="flex items-center justify-center gap-2 rounded-xl border border-[#FF642D]/30 bg-[#FF642D]/10 py-3 text-sm font-semibold text-[#FF642D] transition-all hover:bg-[#FF642D]/20"
            >
              Run a free audit on your site
              <ArrowRight size={15} />
            </a>
          </motion.div>

          {/* Right col: v2 widgets */}
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            whileInView={{ opacity: 1, x: 0 }}
            viewport={{ once: true, margin: "-60px" }}
            transition={{ duration: 0.6, delay: 0.1 }}
            className="space-y-5 lg:col-span-7"
          >
            <TrafficOpportunityCard />
            <NicheBenchmarkWidget />
          </motion.div>
        </div>
      </div>
    </section>
  );
}
