import { clampTitle, clampDesc } from "@/lib/metadata";
import Link from "next/link";

interface PageContent {
  title: string;
  description: string;
  canonical: string;
  intro: string;
  sections: { heading: string; body: string }[];
  bullets: string[];
  cta: string;
}

const pages: Record<string, PageContent> = {
  "seo-audit-for-small-business": {
    title: "SEO Audit for Small Business",
    description:
      "Find the technical SEO issues and quick wins that move the needle for small business websites — without the enterprise price tag.",
    canonical: "https://rankypulse.com/seo-audit-for-small-business",
    intro:
      "Small businesses don't have the luxury of wasting time on low-impact SEO tasks. RankyPulse audits your site in seconds and surfaces only the issues that actually affect your visibility in local and organic search — ranked by traffic impact, not technical severity. You get a clear list of fixes, not a 200-page report that takes a consultant to decode.",
    sections: [
      {
        heading: "The SEO Issues That Hurt Small Business Sites Most",
        body: "The most common technical SEO problems on small business websites are missing meta descriptions (which reduce click-through rate from Google by an average of 5–7%), pages accidentally set to noindex from a WordPress plugin update, slow mobile load times caused by uncompressed images or render-blocking scripts, and duplicate content from category + tag pages. RankyPulse detects all of these in a single crawl and provides step-by-step fixes written for non-technical business owners — not developers.",
      },
      {
        heading: "Local SEO + Technical SEO in One Audit",
        body: "For small businesses, local SEO signals matter as much as traditional technical SEO. The audit checks whether your NAP (Name, Address, Phone) is consistent across your site and structured data, validates your LocalBusiness schema markup, checks for missing Google Business Profile signals, and flags duplicate location pages that can cannibalise each other in local pack results. Getting your technical foundation right means your Google Business listing, citations, and reviews have a much stronger site to point back to.",
      },
    ],
    bullets: [
      "Priority-ranked issues so you fix what moves traffic first",
      "Plain-English fix guides — no developer required",
      "LocalBusiness schema validation and NAP consistency check",
      "Mobile performance and Core Web Vitals benchmarking",
      "Competitor benchmarking to see where local rivals outrank you",
    ],
    cta: "Run a free SEO audit for your small business — results in 30 seconds.",
  },

  "seo-audit-for-shopify": {
    title: "SEO Audit for Shopify",
    description:
      "Audit Shopify-specific SEO issues including duplicate product URLs, missing metadata, pagination errors, and structured data gaps that cost you organic sales.",
    canonical: "https://rankypulse.com/seo-audit-for-shopify",
    intro:
      "Shopify's default structure creates predictable SEO problems that affect nearly every store: duplicate product URLs generated by collection paths, thin category pages with only a few products, and missing structured data that prevents rich product snippets in Google Shopping. RankyPulse identifies these Shopify-specific issues alongside standard technical SEO problems and provides fixes you can implement without touching Liquid code.",
    sections: [
      {
        heading: "Shopify SEO Issues RankyPulse Detects",
        body: "Shopify creates duplicate product URLs whenever a product is accessed through a collection (e.g., /collections/shirts/products/blue-tee vs /products/blue-tee). Without a canonical tag strategy, both URLs compete for the same ranking. RankyPulse flags every duplicate URL pair, validates that canonical tags are resolving correctly to the primary /products/ path, checks that your sitemap is including the right URLs, and identifies pagination issues in collection pages that prevent Google from crawling your full product catalogue.",
      },
      {
        heading: "Structured Data and Product Snippet Opportunities",
        body: "Google's Product rich results — showing price, availability, and reviews directly in the SERP — require valid Product schema with all required fields. RankyPulse validates your Product, BreadcrumbList, and Organization schema across every product and collection page, identifies missing required properties (price, availability, image, description), and flags review schema that doesn't meet Google's guidelines. Stores with valid rich snippets typically see 15–30% higher click-through rates from product search results.",
      },
    ],
    bullets: [
      "Duplicate URL detection for collection vs product paths",
      "Canonical tag validation across the full product catalogue",
      "Product schema validation for rich snippet eligibility",
      "Sitemap integrity check for collection and product pages",
      "Page speed audit for Shopify themes and third-party app scripts",
    ],
    cta: "Audit your Shopify store for free — find the issues costing you sales.",
  },

  "seo-audit-for-wordpress": {
    title: "SEO Audit for WordPress",
    description:
      "Run a WordPress SEO audit to find technical issues, plugin conflicts, and on-page gaps across posts, pages, and archives — with fixes for Yoast, Rank Math, and more.",
    canonical: "https://rankypulse.com/seo-audit-for-wordpress",
    intro:
      "WordPress is the most SEO-flexible CMS — and the most SEO-hazardous. A single misconfigured plugin can accidentally noindex your entire site. Category and tag archives create duplicate content at scale. And every additional plugin adds render-blocking scripts that chip away at Core Web Vitals. RankyPulse audits all of these WordPress-specific risks alongside standard technical SEO, giving you a complete picture of what's holding your site back.",
    sections: [
      {
        heading: "WordPress-Specific SEO Problems",
        body: "The most common WordPress SEO issues include: category archives, tag pages, and author archives that create thin duplicate content across hundreds of URLs; the default WordPress permalink structure that produces non-descriptive URLs (/?p=123); media attachment pages that inherit almost no content and compete with parent posts; the 'Search Engines Discouraged' checkbox in Settings > Reading that's accidentally left on after development; and slow page speed caused by loading all plugin CSS and JS sitewide instead of only on relevant pages.",
      },
      {
        heading: "Yoast and Rank Math Validation",
        body: "RankyPulse reads your on-page metadata output from Yoast SEO and Rank Math and validates it against current best practices — checking for focus keyword cannibalisation across posts, verifying that XML sitemaps are correctly excluding noindexed pages, confirming that Open Graph images are being generated for all post types, and flagging missing breadcrumb markup that could unlock rich snippet display in SERPs. The audit works regardless of which SEO plugin you use, and the fix guides include the exact settings path for both Yoast and Rank Math.",
      },
    ],
    bullets: [
      "Detection of accidentally noindexed pages from plugin settings",
      "Archive page thin content and canonicalisation review",
      "Permalink structure and URL readability check",
      "Yoast and Rank Math settings validation",
      "Core Web Vitals audit with plugin-level performance attribution",
    ],
    cta: "Audit your WordPress site free — find hidden issues in 30 seconds.",
  },
};

export async function generateMetadata({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const page = pages[slug as keyof typeof pages];

  if (!page) {
    return { title: "Page Not Found | RankyPulse" };
  }

  return {
    title: { absolute: clampTitle(`${page.title} | RankyPulse`) },
    description: clampDesc(page.description),
    alternates: { canonical: page.canonical },
  };
}

export function generateStaticParams() {
  return Object.keys(pages).map((slug) => ({ slug }));
}

export default async function Page({
  params,
}: {
  params: Promise<{ slug: string }>;
}) {
  const { slug } = await params;
  const page = pages[slug as keyof typeof pages];

  if (!page) {
    return (
      <main style={{ maxWidth: 900, margin: "80px auto", padding: "0 24px" }}>
        <h1>Page not found</h1>
      </main>
    );
  }

  return (
    <main
      style={{
        maxWidth: 820,
        margin: "80px auto",
        padding: "0 24px 80px",
        fontFamily: "Inter, sans-serif",
        color: "#e2e8f0",
        lineHeight: 1.75,
      }}
    >
      {/* Hero */}
      <h1
        style={{
          fontSize: "2.25rem",
          fontWeight: 800,
          color: "#f8fafc",
          marginBottom: "1rem",
          letterSpacing: "-0.02em",
        }}
      >
        {page.title}
      </h1>
      <p
        style={{
          fontSize: "1.125rem",
          color: "#94a3b8",
          marginBottom: "2rem",
          maxWidth: 640,
        }}
      >
        {page.description}
      </p>

      {/* CTA button */}
      <Link
        href="/audit"
        style={{
          display: "inline-block",
          background: "#FF642D",
          color: "#fff",
          fontWeight: 700,
          padding: "0.75rem 1.75rem",
          borderRadius: "0.75rem",
          textDecoration: "none",
          fontSize: "0.95rem",
          marginBottom: "3rem",
        }}
      >
        {page.cta}
      </Link>

      {/* Intro */}
      <p style={{ fontSize: "1rem", color: "#cbd5e1", marginBottom: "2.5rem" }}>
        {page.intro}
      </p>

      {/* Content sections */}
      {page.sections.map((s) => (
        <section key={s.heading} style={{ marginBottom: "2rem" }}>
          <h2
            style={{
              fontSize: "1.375rem",
              fontWeight: 700,
              color: "#f1f5f9",
              marginBottom: "0.75rem",
            }}
          >
            {s.heading}
          </h2>
          <p style={{ color: "#cbd5e1" }}>{s.body}</p>
        </section>
      ))}

      {/* Feature bullets */}
      <section style={{ marginBottom: "3rem" }}>
        <h2
          style={{
            fontSize: "1.375rem",
            fontWeight: 700,
            color: "#f1f5f9",
            marginBottom: "1rem",
          }}
        >
          What This Audit Checks
        </h2>
        <ul style={{ paddingLeft: "1.25rem", color: "#94a3b8" }}>
          {page.bullets.map((b) => (
            <li key={b} style={{ marginBottom: "0.5rem" }}>
              {b}
            </li>
          ))}
        </ul>
      </section>

      {/* Footer CTA */}
      <div
        style={{
          borderTop: "1px solid #1e293b",
          paddingTop: "2rem",
          textAlign: "center",
        }}
      >
        <p style={{ color: "#64748b", marginBottom: "1rem" }}>
          Ready to fix your SEO?
        </p>
        <Link
          href="/audit"
          style={{
            display: "inline-block",
            background: "#FF642D",
            color: "#fff",
            fontWeight: 700,
            padding: "0.75rem 2rem",
            borderRadius: "0.75rem",
            textDecoration: "none",
          }}
        >
          Start Free Audit →
        </Link>
      </div>
    </main>
  );
}
