"use client";

/**
 * PdfCoverPage — Hidden from screen view, only visible during PDF capture.
 * Renders a branded cover page for the exported PDF report.
 */
interface PdfCoverPageProps {
    domain: string;
    score: number;
    agencyName?: string;
    agencyLogoUrl?: string;
}

export function PdfCoverPage({
    domain,
    score,
    agencyName,
    agencyLogoUrl,
}: PdfCoverPageProps) {
    const date = new Date().toLocaleDateString("en-US", {
        month: "long",
        year: "numeric",
        day: "numeric",
    });

    const scoreColor =
        score >= 80 ? "#10B981" : score >= 50 ? "#F59E0B" : "#EF4444";

    return (
        <div
            id="pdf-cover"
            // Hidden on screen but captured by html2canvas
            aria-hidden="true"
            style={{
                position: "absolute",
                top: "-9999px",
                left: "-9999px",
                width: "794px", // A4 pixel width @96dpi
                minHeight: "1123px",
                backgroundColor: "#0d0f12",
                color: "white",
                fontFamily: "'DM Sans', sans-serif",
                padding: "80px 64px",
                display: "flex",
                flexDirection: "column",
                justifyContent: "space-between",
            }}
        >
            {/* Header branding */}
            <div style={{ display: "flex", alignItems: "center", gap: "12px" }}>
                {agencyLogoUrl ? (
                    // eslint-disable-next-line @next/next/no-img-element
                    <img
                        src={agencyLogoUrl}
                        alt="Agency Logo"
                        style={{ height: "48px", objectFit: "contain" }}
                    />
                ) : (
                    <div
                        style={{
                            fontSize: "28px",
                            fontWeight: 700,
                            color: "#6366f1",
                            letterSpacing: "-1px",
                        }}
                    >
                        RankyPulse
                    </div>
                )}
                {agencyName && (
                    <div style={{ fontSize: "20px", fontWeight: 600, color: "#e5e7eb" }}>
                        {agencyName}
                    </div>
                )}
            </div>

            {/* Main content */}
            <div>
                <div style={{ fontSize: "14px", color: "#6b7280", marginBottom: "8px" }}>
                    SEO AUDIT REPORT
                </div>
                <div
                    style={{
                        fontSize: "40px",
                        fontWeight: 700,
                        color: "#f9fafb",
                        marginBottom: "16px",
                    }}
                >
                    {domain}
                </div>
                <div
                    style={{
                        display: "inline-flex",
                        alignItems: "center",
                        gap: "12px",
                        backgroundColor: "rgba(255,255,255,0.05)",
                        borderRadius: "12px",
                        padding: "16px 24px",
                        marginBottom: "40px",
                    }}
                >
                    <span style={{ fontSize: "56px", fontWeight: 700, color: scoreColor }}>
                        {score}
                    </span>
                    <span style={{ fontSize: "24px", color: "#6b7280" }}>/100</span>
                    <span style={{ fontSize: "14px", color: "#9ca3af" }}>SEO Score</span>
                </div>
                <div style={{ fontSize: "24px", fontWeight: 300, color: "#9ca3af", lineHeight: 1.5 }}>
                    A comprehensive technical SEO analysis covering performance, crawlability,
                    on-page factors, and actionable improvements.
                </div>
            </div>

            {/* Footer */}
            <div
                style={{
                    display: "flex",
                    justifyContent: "space-between",
                    alignItems: "center",
                    borderTop: "1px solid rgba(255,255,255,0.1)",
                    paddingTop: "24px",
                    fontSize: "13px",
                    color: "#4b5563",
                }}
            >
                <span>Generated by {agencyName ?? "RankyPulse"}</span>
                <span>{date}</span>
            </div>
        </div>
    );
}
